### ISSUE TITLE
Watchdog on btController, any ideas?

### ISSUE THREAD

**Issue by DTTerastar** [h2zero/NimBLE-Arduino#351]
```
E (401988) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (401988) task_wdt:  - IDLE0 (CPU 0)
E (401988) task_wdt: Tasks currently running:
E (401988) task_wdt: CPU 0: btController
E (401988) task_wdt: CPU 1: IDLE1
E (401988) task_wdt: Aborting.
abort() was called at PC 0x4018a23c on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x4008f658:0x3ffbfee0 0x4008f8d5:0x3ffbff00 0x4018a23c:0x3ffbff20 0x4008dd01:0x3ffbff40 0x40190881:0x3ffb61d0 0x40190e55:0x3ffb61f0 0x400908e6:0x3ffb6220
  #0  0x4008f658:0x3ffbfee0 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #1  0x4008f8d5:0x3ffbff00 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #2  0x4018a23c:0x3ffbff20 in task_wdt_isr at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/task_wdt.c:252
  #3  0x4008dd01:0x3ffbff40 in _xt_lowint1 at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/xtensa_vectors.S:1154
  #4  0x40190881:0x3ffb61d0 in r_rw_schedule at ??:?
  #5  0x40190e55:0x3ffb61f0 in btdm_controller_task at ??:?
  #6  0x400908e6:0x3ffb6220 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
```

**Comment by h2zero** [comment]
Do you have any tasks that run on core 0? Only time I've ever encountered this is when a task on the same core as the stack takes too much time.

**Comment by DTTerastar** [comment]
Doesn't the wdt get fed in between tasks?  How could something other than btController make btController take too long?

**Comment by DTTerastar** [comment]
I was on a pre-[1.3.4] and i haven't seen it since upgrading to 1.3.6 so maybe it's fixed in the new version?

**Comment by h2zero** [comment]
>I was on a pre-[1.3.4] and i haven't seen it since upgrading to 1.3.6 so maybe it's fixed in the new version?

Are you using the latest arduino core? If so, that could be the reason for the fix with 1.3.6.

**Comment by DTTerastar** [comment]
I did just upgrade to 3.5 (from 3.3) right before seeing that wdt panic.

**Comment by DTTerastar** [comment]
Haven't been able to repro this anymore.  Closing

**Comment by TheHolyRoger** [comment]
@h2zero I'm still getting this same watchdog error:
```
14:26:53.038 -> E (4743686) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
14:26:53.038 -> E (4743686) task_wdt:  - IDLE0 (CPU 0)
14:26:53.038 -> E (4743686) task_wdt: Tasks currently running:
14:26:53.038 -> E (4743686) task_wdt: CPU 0: btController
14:26:53.038 -> E (4743686) task_wdt: CPU 1: IDLE1
14:26:53.038 -> E (4743686) task_wdt: Aborting.
14:26:53.038 -> abort() was called at PC 0x4015d81c on core 0
```

This is happening outside of my loop, in between scans. The above crash actually happened 2 seconds before my next scan was about to start. During that testing session every scan was happening at 55 seconds past the minute.

Last successful scan log:
```
14:25:55.901 -> Checking Bluetooth scan.
14:25:56.396 -> Starting Bluetooth scan.
14:25:59.420 -> Bluetooth scan end called, parsing.
14:25:59.420 -> BT Devices found: 0
14:25:59.420 -> BT Devices ignored: 2
14:25:59.420 -> Clearing Bluetooth results.
14:25:59.420 -> Bluetooth scan done.
```

As far as I can tell this is unrelated to my code since it's not occurring inside my loop or during a scan, device is essentially idle.

Setup code:
```
    NimBLEDevice::setPower(ESP_PWR_LVL_P9);
    pScan = NimBLEDevice::getScan();
    pScan->setInterval(60);
    pScan->setWindow(60);
    pScan->setDuplicateFilter(false);
    pScan->setActiveScan(true);
    pScan->setMaxResults(50);
```

**Comment by h2zero** [comment]
Without knowing more about the code I can't suggest much to help.

Try breaking down the code to a minimal application that only scans then add the removed stuff back in until it breaks.

**Comment by TheHolyRoger** [comment]
@h2zero I was calling nimble and setting up the scan in my `setup()` then as part of my loop calling `pscan->start` with a callback every 60 seconds but these panics were happening only when the loop task wasn't busy (e.g. returning voids until timer hits).

I've just been searching the issues here though, am I right in thinking best practice is to `deinit` after each scan and set it up again before each scan?

I'm trying it this way now to see if it's more stable as hopefully the bluetooth stack will be closed between scans so there can't be anything running to panic while idle

**Comment by h2zero** [comment]
There shouldn't be any need to deinit the stack. 

Does your loop simply start the scan then delay for x time? Any other tasks?

**Comment by TheHolyRoger** [comment]
@h2zero I start the scan with this (have played with 3-15 seconds, panics happened just the same):

```c++
pScan->start(3, scanEndedCB, false);
```

I have a callback which logs `Bluetooth scan done.` when it finishes as shown in the log above.

My `loop()` simply checks a lastScan variable, and if 60 seconds has passed then it will start a scan.

But as you can see the panic's are happening during "idle" periods when the loop is just looping waiting for the next scan time.

Scan finished:
`14:25:59.420`

Panic @:
`14:26:53.038`

Next scan was due to start in 2 seconds time @:
`14:26:55.901`

But as mentioned above I haven't had a single crash since calling `deinit` after every scan and setting it up again before each scan now

**Comment by h2zero** [comment]
Thanks, I'll try to reproduce this. Could you share a minimal code snippet I could use? Also what version of arduino core/nimble are you using?

**Comment by TheHolyRoger** [comment]
Board: DOIT ESP32 DEVKIT V1
Arduino 1.8.19
NimBLE-Arduino 1.4.0

Here's a stripped down version of the code, I've commented out the deinit call which appears to be the fix:
```c++

#include <NimBLEDevice.h>
#include <analogWrite.h>


#define ENABLE_BLUETOOTH_SCAN 1                     // Change this to 1 to enable Bluetooth scan

/* Polling Settings */
static const bool printSerialOutputForDebugging = true;
static const int LOOP_INTERVAL_MS = 10;
static const int bluetoothScanInterval = 60000;

/* BT Settings */
static const bool printAllBluetoothDevices = true;
static const bool printKnownBluetoothDevices = true;
static const int bluetoothMinRSSI = -72;

static std::map<std::string, std::string> bluetoothDevicesIgnored = {
  { "device_name", "00:00:01:02:00:32" }
};


static bool bluetoothSetupCompleted = false;
static long previousBTScan = bluetoothScanInterval;


#if ENABLE_BLUETOOTH_SCAN == 1
  BLEScan* pScan;
  static bool bluetooth_scan_in_progress = false;
  static bool bluetooth_results_parse_in_progress = false;
  static bool bluetooth_scan_finished = false;
  static std::map<std::string, std::string> knownDevices = {};
  static std::string bluetooth_mac_address = "";
#endif

struct to_lower {
  int operator() ( int ch )
  {
    return std::tolower ( ch );
  }
};


#if ENABLE_BLUETOOTH_SCAN == 1

  void deinit_bluetooth() {
    NimBLEDevice::deinit(true);
    pScan = nullptr;
    bluetoothSetupCompleted = false;
  }

  void init_bluetooth(bool firstTimeSetup = false) {
    if (printSerialOutputForDebugging) {
      Serial.println("Starting NimBLE Client");
    }

    NimBLEDevice::init("");
    NimBLEDevice::setPower(ESP_PWR_LVL_P9);
    if (firstTimeSetup) {
      set_bluetooth_mac();
    }
    pScan = NimBLEDevice::getScan();
    pScan->setInterval((int)((bluetoothScanInterval / 4) / 1000));
    pScan->setWindow((int)((bluetoothScanInterval / 4) / 1000));
    // pScan->setInterval(BLE_GAP_SCAN_SLOW_INTERVAL1);
    // pScan->setWindow(BLE_GAP_SCAN_SLOW_WINDOW1);
    pScan->setDuplicateFilter(false);
    pScan->setActiveScan(true);
    pScan->setMaxResults(50);

    bluetoothSetupCompleted = true;
  }

  void set_bluetooth_mac() {
    if (printSerialOutputForDebugging) {
      Serial.print("Bluetooth MAC: ");
      Serial.println(NimBLEDevice::getAddress().toString().c_str());
    }
    bluetooth_mac_address = NimBLEDevice::getAddress().toString();
  }

#endif


void setup () {

  Serial.begin(115200);

  #if ENABLE_BLUETOOTH_SCAN == 1
    init_bluetooth(true);
  #endif

}


#if ENABLE_BLUETOOTH_SCAN == 1
  void printKnownDevices() {
    std::map<std::string, std::string>::iterator it = knownDevices.begin();
    while (it != knownDevices.end())
    {
      std::string aName = it->first;
      std::string anAddr = it->second;
      std::transform(anAddr.begin(), anAddr.end(), anAddr.begin(), to_lower());
      std::replace( aName.begin(), aName.end(), ' ', '_');
      if (printSerialOutputForDebugging) {
        Serial.print("BT Device known: ");
        Serial.print(aName.c_str());
        Serial.print(" - ");
        Serial.println(anAddr.c_str());
      }
      it++;
    }
    Serial.print("BT Devices known: ");
    Serial.println(knownDevices.size());
  }

  void scanEndedCB(NimBLEScanResults results) {
    if (bluetooth_results_parse_in_progress) {
      return;
    }
    bluetooth_results_parse_in_progress = true;
    if (printSerialOutputForDebugging) {
      Serial.println("Bluetooth scan end called, parsing.");
    }
    NimBLEDevice::getScan()->stop();
    std::vector<NimBLEAdvertisedDevice*>::iterator it = results.begin();
    std::string devAddr;
    std::string devName;
    int devRSSI;
    int devicesFound = 0;
    int devicesIgnored = 0;
    while (it != results.end())
    {
      NimBLEAdvertisedDevice* aDev = *it;
      devName = aDev->getName().c_str();
      devAddr = aDev->getAddress().toString();
      devRSSI = aDev->getRSSI();
      bool deviceIgnored = false;
      std::map<std::string, std::string>::iterator iD = bluetoothDevicesIgnored.begin();
      while (iD != bluetoothDevicesIgnored.end())
      {
        std::string aName = iD->first;
        std::string anAddr = iD->second;
        std::transform(anAddr.begin(), anAddr.end(), anAddr.begin(), to_lower());
        std::replace( aName.begin(), aName.end(), ' ', '_');
        if (anAddr == devAddr) {
          deviceIgnored = true;
        }
        iD++;
      }

      if (!deviceIgnored && devRSSI > bluetoothMinRSSI) {
        devicesFound++;

        if (printSerialOutputForDebugging && printAllBluetoothDevices) {
          Serial.print("BT Device found: ");
          Serial.print(aDev->toString().c_str());
          Serial.print(" - RSSI: ");
          Serial.println(devRSSI);
        }
        if (devName.size() > 0) {
          knownDevices[devName] = devAddr.c_str();
        }
      }
      else if (deviceIgnored) {
        devicesIgnored++;
      }

      it++;
    }
    if (printSerialOutputForDebugging) {
      if (printAllBluetoothDevices) {
        Serial.print("BT Devices found: ");
        Serial.println(devicesFound);
      }
      if (printKnownBluetoothDevices) {
        printKnownDevices();
      }
      Serial.print("BT Devices ignored: ");
      Serial.println(devicesIgnored);
    }
    delay(50);

    if (printSerialOutputForDebugging) {
      Serial.println("Clearing Bluetooth results.");
    }
    pScan->clearResults();
    if (printSerialOutputForDebugging) {
      Serial.println("Bluetooth scan done.");
    }
    delay(50);
    bluetooth_scan_in_progress = false;
    bluetooth_results_parse_in_progress = false;
    bluetooth_scan_finished = true;

  }

  void scan_bluetooth () {
    // if (bluetooth_scan_finished) {
    //   bluetooth_scan_finished = false;
    //   if (printSerialOutputForDebugging) {
    //     Serial.println("Deinit Bluetooth.");
    //   }
    //   deinit_bluetooth();
    // }
    if ((millis() - previousBTScan) >= bluetoothScanInterval && !bluetooth_scan_in_progress) {
      previousBTScan = millis();
      bluetooth_scan_in_progress = true;
      if (printSerialOutputForDebugging) {
        Serial.println("Checking Bluetooth scan.");
      }
      if(!bluetooth_results_parse_in_progress && (pScan && pScan->isScanning() == false) || !pScan) {
        delay(500);

        if (printSerialOutputForDebugging) {
          Serial.println("Starting Bluetooth scan.");
        }
        if (!bluetoothSetupCompleted) {
          init_bluetooth();
        }
        delay(50);
        pScan->start(3, scanEndedCB, false);
      }
    } else {
      bluetooth_scan_in_progress = false;
    }
  }
#endif

void loop () {
  vTaskDelay(LOOP_INTERVAL_MS / portTICK_PERIOD_MS);
  #if ENABLE_BLUETOOTH_SCAN == 1
    scan_bluetooth();
  #endif
}

```

**Comment by TheHolyRoger** [comment]
@h2zero is it related to this? https://github.com/espressif/esp-idf/issues/4719

**Comment by h2zero** [comment]
That's a pretty old issue, I would assume it's no longer relevant.
